#pragma once

#include <initializer_list>

namespace Musae::SimFlux {

constexpr auto defaultMacro = {
    "#############################################################################",
    "# Initialization settings",
    "#############################################################################",
    "",
    "/control/verbose 2",
    "/control/saveHistory",
    "/run/verbose 2",
    "",
    "#/Mustard/Detector/Description/Import SimFlux.yaml",
    "",
    "/run/initialize",
    "",
    "/Musae/Physics/NonMuonProcessActivation no",
    "",
    "/Mustard/Generator/FromDataPrimaryGenerator/EventData crmu.root CRMu",
    "",
    "/Mustard/Analysis/FilePath SimFlux_vis",
    "/Mustard/Analysis/FileMode RECREATE",
    "",

#if MUSTARD_USE_G4VIS

    "#############################################################################",
    "# Visualization settings",
    "#############################################################################",
    "",
    "/vis/open OGL",
    "",
    "/vis/viewer/set/autoRefresh no",
    "/vis/verbose errors",
    "",
    "/vis/drawVolume",
    "",
    "/vis/viewer/set/upVector 0 0 1",
    "/vis/viewer/set/viewpointVector 0 -1 0.01",
    "#/vis/viewer/set/rotationStyle freeRotation",
    "/vis/viewer/set/projection p",
    "/vis/viewer/set/style s",
    "#/vis/viewer/set/style w",
    "#/vis/viewer/set/hiddenEdge yes",
    "/vis/viewer/set/auxiliaryEdge no",
    "#/vis/viewer/set/lineSegmentsPerCircle 100",
    "#/vis/viewer/zoom 50",
    "",
    "/vis/geometry/set/visibility World 0 no",
    "# Colors",
    "/vis/geometry/set/colour Terrain          0     1     1     1     0.5",
    "/vis/geometry/set/colour LGA              0     0     1     0     1",
    "/vis/geometry/set/colour LGAScintillator  0     0     1     1     1",
    "",
    "/vis/scene/add/date",
    "/vis/scene/add/axes 0 0 0 100 m",
    "/vis/scene/add/trajectories smooth #rich",
    "/vis/scene/add/hits",
    "",
    "/vis/filtering/trajectories/create/particleFilter",
    "/vis/filtering/trajectories/particleFilter-0/add nu_e",
    "/vis/filtering/trajectories/particleFilter-0/add nu_mu",
    "/vis/filtering/trajectories/particleFilter-0/add nu_tau",
    "/vis/filtering/trajectories/particleFilter-0/add anti_nu_e",
    "/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu",
    "/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau",
    "/vis/filtering/trajectories/particleFilter-0/invert yes",
    "",
    "/vis/modeling/trajectories/create/drawByCharge",
    "/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts no",
    "/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 1",
    "/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSizeType screen",
    "/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsType dots",
    "/vis/modeling/trajectories/drawByCharge-0/default/setDrawLine yes",
    "/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 1",
    "/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts yes",
    "/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1",
    "/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSizeType screen",
    "/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsType dots",
    "",
    "/vis/scene/endOfEventAction accumulate",
    "",
    "/vis/verbose warnings",
    "/vis/viewer/set/autoRefresh yes",

#endif

    ""};

} // namespace Musae::SimFlux
