#############################################################################
# Initialization settings
#############################################################################

/control/verbose 2
/control/saveHistory
/run/verbose 2

/Mustard/Detector/Description/Import ../scripts/Example2_fs.yaml

/run/initialize

/Musae/Physics/NonMuonProcessActivation no
/Musae/Physics/PerfectRangeGeneration no

/Mustard/Analysis/FilePath ../data/SimFlux_vis/SimFlux_test
/Mustard/Analysis/FileMode RECREATE

/Mustard/Generator/FromDataPrimaryGenerator/EventData ../data/GenCRMu/Tianqin_sky_1e8_p15_z60_b100_r3_9_26/* CRMu

/tracking/verbose 2
#/run/verbose 2

#############################################################################
# Visualization settings
#############################################################################

/vis/open OGL

/vis/viewer/set/autoRefresh no
/vis/verbose errors

/vis/drawVolume

/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointVector 0 -1 0.01
#/vis/viewer/set/rotationStyle freeRotation
/vis/viewer/set/projection p
/vis/viewer/set/style s
#/vis/viewer/set/style w
#/vis/viewer/set/hiddenEdge yes
/vis/viewer/set/auxiliaryEdge no
#/vis/viewer/set/targetPoint -349330.00000004654 -8512.999999720591 515798.46 mm
#/vis/viewer/set/lineSegmentsPerCircle 100
#/vis/viewer/zoom 50

/vis/geometry/set/visibility World 0 no

# Colors
/vis/geometry/set/colour Terrain          0     1     1     1     0.5
/vis/geometry/set/colour LGA              0     0     1     0     1
/vis/geometry/set/colour LGAScintillator  0     0     1     1     1

/vis/scene/add/date
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories smooth #rich
/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add nu_e
/vis/filtering/trajectories/particleFilter-0/add nu_mu
/vis/filtering/trajectories/particleFilter-0/add nu_tau
/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
/vis/filtering/trajectories/particleFilter-0/add anti_nu_mu
/vis/filtering/trajectories/particleFilter-0/add anti_nu_tau
/vis/filtering/trajectories/particleFilter-0/invert yes

/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts no
/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSize 1
/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsSizeType screen
/vis/modeling/trajectories/drawByCharge-0/default/setAuxPtsType dots
/vis/modeling/trajectories/drawByCharge-0/default/setDrawLine yes
/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 3
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts yes
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSizeType screen
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsType dots

/vis/scene/endOfEventAction accumulate

/vis/verbose warnings
/vis/viewer/set/autoRefresh yes

#/vis/scene/add/arrow 0 0 0 -850000 0 0 mm
#/vis/scene/add/arrow -171450.00000004657 135790.0000002794 -54628.846 -171450.00000004657 135790.0000002794 10000 mm
#/vis/scene/add/text -171450.00000004657 135790.0000002794 -54628.846 mm 24 0 0 "A"
#/vis/scene/add/arrow -200730.00000004657 95870.0000002794 -54418.846 -200730.00000004657 95870.0000002794 10000 mm
#/vis/scene/add/text -200730.00000004657 95870.0000002794 -54418.846 mm 24 0 0 "B"
#/vis/scene/add/arrow -246080.00000004657 117350.00000027941 -54278.846 -246080.00000004657 117350.00000027941 10000 mm
#/vis/scene/add/text -246080.00000004657 117350.00000027941 -54278.846 mm 24 0 0 "C"